# =====================================================================
# ARKA build-time server configuration (Windows / PowerShell)
# =====================================================================
# These four values are baked into the binary at COMPILE TIME (read via
# `option_env!` in libs/hbb_common/src/config.rs and src/common.rs).
# The resulting client connects to the Arka server with ZERO end-user setup,
# and the server fields are locked in the UI (see ARKA_CUSTOMIZATION.md).
#
# HOW TO USE:
#   1. Replace the 4 placeholder values below with the real Arka values.
#   2. Dot-source this file in the SAME shell you build from:
#         . .\arka-env.ps1
#   3. Build (see ARKA_CUSTOMIZATION.md, "Build" section).
#
# Leave a value as "" to fall back to RustDesk defaults for that one item.
# ---------------------------------------------------------------------

# ID / Rendezvous server (host or host:port). Example: "id.arka.ir" or "1.2.3.4"
$env:RENDEZVOUS_SERVER = "<ID_SERVER_IP_OR_DOMAIN>"

# Relay server (optional; usually the same host as ID unless separated)
$env:RELAY_SERVER      = "<RELAY_IP_OR_DOMAIN>"

# API server (for web console / login). Example: "https://api.arka.ir"
$env:API_SERVER        = "https://<API_DOMAIN>"

# hbbs public key, base64 (contents of id_ed25519.pub generated by hbbs)
$env:RS_PUB_KEY        = "<BASE64_PUBLIC_KEY>"

Write-Host "ARKA build env set:" -ForegroundColor Cyan
Write-Host "  RENDEZVOUS_SERVER = $env:RENDEZVOUS_SERVER"
Write-Host "  RELAY_SERVER      = $env:RELAY_SERVER"
Write-Host "  API_SERVER        = $env:API_SERVER"
Write-Host "  RS_PUB_KEY        = $($env:RS_PUB_KEY.Substring(0, [Math]::Min(12, $env:RS_PUB_KEY.Length)))..."
