#!/usr/bin/env bash
# =====================================================================
# ARKA build-time server configuration (Linux / macOS / bash)
# =====================================================================
# These four values are baked into the binary at COMPILE TIME (read via
# `option_env!` in libs/hbb_common/src/config.rs and src/common.rs).
# The resulting client connects to the Arka server with ZERO end-user setup,
# and the server fields are locked in the UI (see ARKA_CUSTOMIZATION.md).
#
# HOW TO USE:
#   1. Replace the 4 placeholder values below with the real Arka values.
#   2. Source this file in the SAME shell you build from:
#         source ./arka-env.sh
#   3. Build (see ARKA_CUSTOMIZATION.md, "Build" section).
#
# Leave a value empty ("") to fall back to RustDesk defaults for that item.
# ---------------------------------------------------------------------

# ID / Rendezvous server (host or host:port). Example: "id.arka.ir" or "1.2.3.4"
export RENDEZVOUS_SERVER="<ID_SERVER_IP_OR_DOMAIN>"

# Relay server (optional; usually the same host as ID unless separated)
export RELAY_SERVER="<RELAY_IP_OR_DOMAIN>"

# API server (for web console / login). Example: "https://api.arka.ir"
export API_SERVER="https://<API_DOMAIN>"

# hbbs public key, base64 (contents of id_ed25519.pub generated by hbbs)
export RS_PUB_KEY="<BASE64_PUBLIC_KEY>"

echo "ARKA build env set:"
echo "  RENDEZVOUS_SERVER = ${RENDEZVOUS_SERVER}"
echo "  RELAY_SERVER      = ${RELAY_SERVER}"
echo "  API_SERVER        = ${API_SERVER}"
echo "  RS_PUB_KEY        = ${RS_PUB_KEY:0:12}..."
